title: Textile Technologies
description: Green-tech themed site

# User/Org site settings
url: "https://esalvadorit.github.io"
baseurl: "/TextileTechnologies.github.io"

# Theme (GitHub Pages–compatible)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
