title: Textile Technologies
description: Green-tech themed site

# User/Org site settings
url: "https://textiletechnologies.github.io"  # full site URL
baseurl: ""                                   # must be empty for user/org sites

# Theme (GitHub Pages–compatible)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
